// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBm9gVEFLsICZ8e0SFt9YSjkLtDMoEFgM',
    appId: '1:962371970108:web:a1edd30d1c9d1930408f39',
    messagingSenderId: '962371970108',
    projectId: 'weather-app-ee71b',
    authDomain: 'weather-app-ee71b.firebaseapp.com',
    storageBucket: 'weather-app-ee71b.appspot.com',
    measurementId: 'G-29QZVV9EL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA31aEQJ698NxEtAcyxPUqGtDBbo_TAaIo',
    appId: '1:962371970108:android:279d59ceb832e496408f39',
    messagingSenderId: '962371970108',
    projectId: 'weather-app-ee71b',
    storageBucket: 'weather-app-ee71b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeqBFMcHFiSmKm79Ul-HZYkXafILgHFyI',
    appId: '1:962371970108:ios:64548fc583022e20408f39',
    messagingSenderId: '962371970108',
    projectId: 'weather-app-ee71b',
    storageBucket: 'weather-app-ee71b.appspot.com',
    iosClientId: '962371970108-i120ing3rvevtc7f35pif4l0hntg9p4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.lesson1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeqBFMcHFiSmKm79Ul-HZYkXafILgHFyI',
    appId: '1:962371970108:ios:64548fc583022e20408f39',
    messagingSenderId: '962371970108',
    projectId: 'weather-app-ee71b',
    storageBucket: 'weather-app-ee71b.appspot.com',
    iosClientId: '962371970108-i120ing3rvevtc7f35pif4l0hntg9p4n.apps.googleusercontent.com',
    iosBundleId: 'com.example.lesson1',
  );
}
